// All 50 constituents of the Nifty 50 index with Yahoo Finance .NS suffix
export const NIFTY50_SYMBOLS = [
  'RELIANCE.NS',
  'TCS.NS',
  'HDFCBANK.NS',
  'INFY.NS',
  'ICICIBANK.NS',
  'HINDUNILVR.NS',
  'ITC.NS',
  'SBIN.NS',
  'BHARTIARTL.NS',
  'KOTAKBANK.NS',
  'LT.NS',
  'BAJFINANCE.NS',
  'HCLTECH.NS',
  'ASIANPAINT.NS',
  'AXISBANK.NS',
  'MARUTI.NS',
  'TITAN.NS',
  'SUNPHARMA.NS',
  'ULTRACEMCO.NS',
  'WIPRO.NS',
  'ONGC.NS',
  'NTPC.NS',
  'NESTLEIND.NS',
  'BAJAJFINSV.NS',
  'POWERGRID.NS',
  'M&M.NS',
  'TATAMOTORS.NS',
  'TECHM.NS',
  'ADANIPORTS.NS',
  'ADANIENT.NS',
  'GRASIM.NS',
  'BPCL.NS',
  'DIVISLAB.NS',
  'DRREDDY.NS',
  'EICHERMOT.NS',
  'HEROMOTOCO.NS',
  'HINDALCO.NS',
  'INDUSINDBK.NS',
  'JSWSTEEL.NS',
  'CIPLA.NS',
  'APOLLOHOSP.NS',
  'TATACONSUM.NS',
  'COALINDIA.NS',
  'BRITANNIA.NS',
  'BAJAJ-AUTO.NS',
  'SBILIFE.NS',
  'HDFCLIFE.NS',
  'TATASTEEL.NS',
  'UPL.NS',
  'BEL.NS',
];

// Friendly short names for display
export const SYMBOL_NAMES = {
  'RELIANCE.NS': 'Reliance',
  'TCS.NS': 'TCS',
  'HDFCBANK.NS': 'HDFC Bank',
  'INFY.NS': 'Infosys',
  'ICICIBANK.NS': 'ICICI Bank',
  'HINDUNILVR.NS': 'HUL',
  'ITC.NS': 'ITC',
  'SBIN.NS': 'SBI',
  'BHARTIARTL.NS': 'Airtel',
  'KOTAKBANK.NS': 'Kotak Bank',
  'LT.NS': 'L&T',
  'BAJFINANCE.NS': 'Bajaj Finance',
  'HCLTECH.NS': 'HCL Tech',
  'ASIANPAINT.NS': 'Asian Paints',
  'AXISBANK.NS': 'Axis Bank',
  'MARUTI.NS': 'Maruti',
  'TITAN.NS': 'Titan',
  'SUNPHARMA.NS': 'Sun Pharma',
  'ULTRACEMCO.NS': 'UltraTech',
  'WIPRO.NS': 'Wipro',
  'ONGC.NS': 'ONGC',
  'NTPC.NS': 'NTPC',
  'NESTLEIND.NS': 'Nestle',
  'BAJAJFINSV.NS': 'Bajaj Finserv',
  'POWERGRID.NS': 'Power Grid',
  'M&M.NS': 'M&M',
  'TATAMOTORS.NS': 'Tata Motors',
  'TECHM.NS': 'Tech Mahindra',
  'ADANIPORTS.NS': 'Adani Ports',
  'ADANIENT.NS': 'Adani Ent',
  'GRASIM.NS': 'Grasim',
  'BPCL.NS': 'BPCL',
  'DIVISLAB.NS': "Divi's Lab",
  'DRREDDY.NS': "Dr Reddy's",
  'EICHERMOT.NS': 'Eicher Motors',
  'HEROMOTOCO.NS': 'Hero Moto',
  'HINDALCO.NS': 'Hindalco',
  'INDUSINDBK.NS': 'IndusInd Bank',
  'JSWSTEEL.NS': 'JSW Steel',
  'CIPLA.NS': 'Cipla',
  'APOLLOHOSP.NS': 'Apollo Hosp',
  'TATACONSUM.NS': 'Tata Consumer',
  'COALINDIA.NS': 'Coal India',
  'BRITANNIA.NS': 'Britannia',
  'BAJAJ-AUTO.NS': 'Bajaj Auto',
  'SBILIFE.NS': 'SBI Life',
  'HDFCLIFE.NS': 'HDFC Life',
  'TATASTEEL.NS': 'Tata Steel',
  'UPL.NS': 'UPL',
  'BEL.NS': 'BEL',
};

// Sector mapping for each stock
export const SYMBOL_SECTORS = {
  'RELIANCE.NS': 'Energy',
  'TCS.NS': 'IT',
  'HDFCBANK.NS': 'Banking',
  'INFY.NS': 'IT',
  'ICICIBANK.NS': 'Banking',
  'HINDUNILVR.NS': 'FMCG',
  'ITC.NS': 'FMCG',
  'SBIN.NS': 'Banking',
  'BHARTIARTL.NS': 'Telecom',
  'KOTAKBANK.NS': 'Banking',
  'LT.NS': 'Infra',
  'BAJFINANCE.NS': 'Finance',
  'HCLTECH.NS': 'IT',
  'ASIANPAINT.NS': 'Consumer',
  'AXISBANK.NS': 'Banking',
  'MARUTI.NS': 'Auto',
  'TITAN.NS': 'Consumer',
  'SUNPHARMA.NS': 'Pharma',
  'ULTRACEMCO.NS': 'Cement',
  'WIPRO.NS': 'IT',
  'ONGC.NS': 'Energy',
  'NTPC.NS': 'Energy',
  'NESTLEIND.NS': 'FMCG',
  'BAJAJFINSV.NS': 'Finance',
  'POWERGRID.NS': 'Energy',
  'M&M.NS': 'Auto',
  'TATAMOTORS.NS': 'Auto',
  'TECHM.NS': 'IT',
  'ADANIPORTS.NS': 'Infra',
  'ADANIENT.NS': 'Conglomerate',
  'GRASIM.NS': 'Diversified',
  'BPCL.NS': 'Energy',
  'DIVISLAB.NS': 'Pharma',
  'DRREDDY.NS': 'Pharma',
  'EICHERMOT.NS': 'Auto',
  'HEROMOTOCO.NS': 'Auto',
  'HINDALCO.NS': 'Metals',
  'INDUSINDBK.NS': 'Banking',
  'JSWSTEEL.NS': 'Metals',
  'CIPLA.NS': 'Pharma',
  'APOLLOHOSP.NS': 'Healthcare',
  'TATACONSUM.NS': 'FMCG',
  'COALINDIA.NS': 'Energy',
  'BRITANNIA.NS': 'FMCG',
  'BAJAJ-AUTO.NS': 'Auto',
  'SBILIFE.NS': 'Insurance',
  'HDFCLIFE.NS': 'Insurance',
  'TATASTEEL.NS': 'Metals',
  'UPL.NS': 'Agro',
  'BEL.NS': 'Defence',
};
